name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    name: Run check, test and lints
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Install Rust toolchain
        uses: Cardinal-Cryptography/github-actions/install-rust-toolchain@v1
        with:
          targets: wasm32-unknown-unknown
          components: clippy rustfmt


      - name: Run format checks
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all

      - name: Run linter
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets -- --no-deps -D warnings
          


      - name: Run unit test suite
        uses: actions-rs/cargo@v1
        with:
          command: test

          

  
